### ISSUE TITLE
Outdated redoc-cli v0.9.7 therefore not possible with code samples

### ISSUE THREAD

**Issue by elsewhat** [seeebiii/redoc-cli-github-action#2]
Great use of github actions, but unfortunately the redoc-cli from the docker image is a bit outdated with version 0.9.7 and latest is 0.10.2.

Assume this is from the docker base image used in
https://github.com/seeebiii/redoc-cli-github-action/blob/master/Dockerfile#L1

This causes newer redoc-cli functionality such as code samples to not be available. Have already integrated  snippet-enricher-cli https://github.com/cdwv/oas3-api-snippet-enricher as part of an overall repo workflow, but due to the redoc-cli version its not processing the data.

Unfortunately, the official redoc-cli image is not in place yet https://github.com/Redocly/redoc/issues/1158

Any options for fixing?

**Comment by seeebiii** [comment]
Hi @elsewhat , good catch! Exactly, the Docker image is coming from this repo: https://github.com/seeebiii/docker-redoc-cli. I haven't setup any automation to continuously build a new Docker image or so. But I can soon trigger a new one so it gets updated. Maybe I'll find some time to setup automation for it but not in the next few weeks probably.

**Comment by elsewhat** [comment]
Thanks @seeebiii !
For me, the one-time update is the most important as I'd like our customers to have access to code samples generated for redoc
Any update on when this can be done ?

**Comment by seeebiii** [comment]
@elsewhat Sorry, I was busy the past days with some other stuff. I have updated both now, the Docker image and the GitHub Action. Can you check if it's working for you? You should reference this action using `v10`.

**Comment by elsewhat** [comment]
Awesome! Thanks. 
`v10 `seems to be working great. 
Code samples in OpenAPI spec are now being shown in the generated redoc.
![image](https://user-images.githubusercontent.com/1133607/102212365-6649c980-3ed5-11eb-9771-7650ea1d8d90.png)

PS integrated [snippet-enricher-cli](https://github.com/cdwv/oas3-api-snippet-enricher#readme) through github actions to automatically inject code samples into the OpenAPI
      # Install tool to add code snippets
      - name: Install snippet-enricher-cli
        run: npm install snippet-enricher-cli
      # Run tool to add code snippets
      - name: Run snippet-enricher-cli
        run: npx snippet-enricher-cli --input=OpenAPI/maintenance-api.yaml --targets="shell_curl,node_native,python_python3" > openapi-with-examples.json
      # use redoc-cli-github-action to generate your HTML bundle
      - name: redoc-cli
        uses: seeebiii/redoc-cli-github-action@v10

**Comment by seeebiii** [comment]
@elsewhat Nice, that looks good! Thanks for the hint about the snippet enricher, looks interesting!
